### ISSUE TITLE
To ProJakob

### ISSUE THREAD

**Issue by NavineClient** [ProJakob/navineBetaBuilds#1]
So, I am making this response, and as you can see my username is NavineClient. For you, you don't know me, but for me, I know who you are. We are friends on discord and you have helped me with a lot of things, but I have also helped you with many things. For you to know this, I am not golddev nor lily nor anyone apart of golddev. I will make myself known to you on discord when the timing is right. For now, I will be watching you in the shadows, but I am no harm to you nor anyone. I will also be dming you soon when I get the chance to of a new server I have created for your Navine group, but there are some rules you must follow when you join the server. I hope you take this message well and good luck to your project. I support you with your ideas that you add to this project.
- @NavineClient

**Comment by ProJakob** [comment]
Well that seems silly.. I'll be waiting.

**Comment by NavineClient** [comment]
I want you to look at dms soon, there will be a link waiting for you. Once you see my username on instagram you will know who I am. - @NavineClient
