### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NavineClient** [ProJakob/navineBetaBuilds#2]
By Any chance can you make a infinite discord invite of Navine HQ and send it to ur deleted account ( or some random that isn't online anymore ) then send the same invite to here by replying to it. I need a server Invite to the discord server of Navine HQ due to the fact I am making a Minecraft Server that will be needing the invite link for a Skript called /discord. I need it as soon as possible so that I can get the discord Skript finished so that the people that may join the server can do /discord to be able to join the discord server. All I need is a infinite discord invite for Navine HQ and that is all. @ProJakob 

- @NavineClient

Here is what its called to give you a hint on who it is.
![Screenshot 2024-04-02 12 15 33 PM](https://github.com/ProJakob/navineBetaBuilds/assets/163175221/7fd43701-8af4-4446-a855-8310f562d582)

**Comment by ProJakob** [comment]
https://discord.gg/PDXf9D24Ar here you go
